### ISSUE TITLE
how is the unmixing computed?

### ISSUE THREAD

**Issue by qianyizhang** [BTajini/augfmri#3]
and what are the preprocessing steps for resting data?
furthermore, can you elaborate more than the difference between conditional ICA and ICA with covariance?

**Comment by hugorichard** [comment]
The HCP resting state data are reduced using the atlas called "Dictionary of Functional Modes".
I refer you to https://github.com/Parietal-INRIA/DiFuMo so that you can get it.
You can apply it by using the `from nilearn.input_data import NiftiMapsMasker` in python that simply projects the data on the probabilistic atlas using a matrix product.
Once your resting state data have been reduced that way, you just need to apply an ICA algorithm (we use FastICA) to get the unmixing matrices.

On the task experiments, a first difference is that with "ICA with covariance" and our method is that "ICA with covariance" only uses task data and does not use rest data. A second difference is that in ICA with covariance we unmix the data and estimate a covariance from the residual: new data are generated by sampling a noise value and a value for each source, remixing the data and adding the sampled noise . In CondICA we unmix the data, use a quantile transform to "Gaussianize" the data from which we sample. So the generative model is not exactly the same. I refer you to the paper for a better description.

I can describe in more details part of my answer if it is still unclear.

**Comment by qianyizhang** [comment]
thanks for the quick response!
and pardon me for being amateur in the signal decomposition area, i still have 2 questions:
1. does implementation/hyperparameter matter much? in another word, does [sklearn FastICA](https://scikit-learn.org/dev/modules/generated/sklearn.decomposition.FastICA.html#sklearn-decomposition-fastica) work out of the box?
2. there seem to be other decomposition method (PCA variants, NMF variants, GMM variants), which could also fit into your conditional generative framework. Do you think (or even better if you tried) these methods would work? and why/why not?

**Comment by bthirion** [comment]
1. Yes AFAIK
2. We haven't tried other methods. Independence seems the most natural criterion to obtain a good generative model.

**Comment by hugorichard** [comment]
Further on point 1.
The hyperparameter that is assumed to be important in ICA is the number of components. In the paper, you can see that for a large range of components, the data augmentation method works. This seems to indicate that the method is not too sensitive to hyper-parameters. However, we did not try to use other source densities, or other optimization algorithms than FastICA.

**Comment by qianyizhang** [comment]
thanks for answering
